/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database readiness. Used by the compose healthcheck. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email + password login. Sets the httpOnly `session` cookie and returns the user. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an account (no event roles yet) and logs it in. */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the current browser session. */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user and their roles per event. 401 when not logged in. */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public gallery with search and filters. Acceptance checks 1 and 2 read this route. */
        get: operations["GalleryController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One public project, by internal id or fixture id (e.g. prj_01). */
        get: operations["GalleryController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create your team's draft. Refused with 403 `submissions_closed` once the event's
         *     deadline has passed, before the body is validated (acceptance check 3).
         */
        post: operations["SubmissionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/submissions/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Draft or submitted: for its team, the event's organisers and admins (403 otherwise). */
        get: operations["SubmissionController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit any field. Team members only, until the deadline, also after submitting
         *     (403 `submissions_closed` after it).
         */
        patch: operations["SubmissionController_update"];
        trace?: never;
    };
    "/api/submissions/{ref}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the draft (needs a title and a summary); it then appears in the public gallery. */
        post: operations["SubmissionController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own scores. Judges only: participants get 403 (acceptance checks 4 and 6). */
        get: operations["JudgingController_ownScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judges/{judgeRef}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One judge's scores, by internal id or fixture id (e.g. jdg_24). Only that judge, the
         *     event's organisers and admins may read them; any other judge gets 403 (acceptance check 5).
         */
        get: operations["JudgingController_judgeScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/scores.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every review in the event as CSV. Organisers and admins only (acceptance check 7). */
        get: operations["JudgingController_exportScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The rubric with each criterion's share of the score. Public: teams see how they are judged. */
        get: operations["RubricController_get"];
        /**
         * Replace the rubric (1–10 criteria, in display order). The event's organisers and admins.
         *     Once reviews are final: labels and weights can change; adding or removing criteria and
         *     changing a scored range are refused (409 `rubric_locked`).
         */
        put: operations["RubricController_replace"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/assignments/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Top every judged project up to `target` reviews (default 3): track-matched, never a
         *     conflict of interest, least-loaded judge first, seeded random tie-breaks. Existing work is
         *     kept. Reports projects that cannot reach the target. The event's organisers and admins.
         */
        post: operations["AssignmentController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your assigned projects in every event you judge, in queue order, with progress. */
        get: operations["ReviewsController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/reviews/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One of your assignments: the project, the rubric and your review so far. */
        get: operations["ReviewsController_get"];
        /**
         * Save your draft (marks may be missing; null clears one). 409 `review_final` once submitted,
         *     403 `judging_closed` after judging closes.
         */
        put: operations["ReviewsController_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/reviews/{assignmentId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the review: every criterion marked. Final; submitting again changes nothing. */
        post: operations["ReviewsController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Judging progress per judge and per project, with judges who gave every project exactly the
         *     same marks flagged. The event's organisers and admins; the dashboard polls it.
         */
        get: operations["ProgressController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every event, newest deadline first. Public. */
        get: operations["EventsController_list"];
        put?: never;
        /**
         * Create an event; you become its organiser. Admins and existing organisers only (403
         *     otherwise). The slug is derived from the name unless given; a taken slug is 409.
         */
        post: operations["EventsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with its tracks and prizes. Public. */
        get: operations["EventsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the name or dates. Organisers of this event and admins only. */
        patch: operations["EventsController_update"];
        trace?: never;
    };
    "/api/events/{eventRef}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a track. A name already used in this event is 409 `track_name_taken`. */
        post: operations["TracksController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/tracks/{trackRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an unused track. One with submissions, prizes or judges is 409 `track_in_use`. */
        delete: operations["TracksController_remove"];
        options?: never;
        head?: never;
        /** Rename a track. */
        patch: operations["TracksController_rename"];
        trace?: never;
    };
    "/api/events/{eventRef}/prizes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a prize: overall, or for one track of this event. */
        post: operations["PrizesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/prizes/{prizeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["PrizesController_remove"];
        options?: never;
        head?: never;
        /** Change a prize's name, description or track. */
        patch: operations["PrizesController_update"];
        trace?: never;
    };
    "/api/events/{eventRef}/organizers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrganizersController_list"];
        put?: never;
        /**
         * Make an existing account an organiser (404 if no account uses the email). Refused for
         *     someone on a team in the event or judging it (409 `conflict_of_interest`).
         */
        post: operations["OrganizersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/organizers/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove an organiser, yourself included; never the last one (409 `last_organizer`). */
        delete: operations["OrganizersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a team in an event; you become its first member. Only while the event accepts
         *     submissions (403 `submissions_closed` / `submissions_not_open`). One team per person per
         *     event (409 `already_on_team`); team names are unique per event (409 `team_name_taken`).
         */
        post: operations["TeamsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own teams, each with its event and current submission. Any logged-in user. */
        get: operations["TeamsController_mine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A team and its members. Its members, the event's organisers and admins only. */
        get: operations["TeamsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{teamRef}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A new invite link (7 days, 4 uses). Members of the team only, while the event is open. */
        post: operations["TeamsController_createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What an invite link is for. Public, and does not use the invite. 410 when expired or used up. */
        get: operations["TeamsController_preview"];
        put?: never;
        /** Join the invite's team. */
        post: operations["TeamsController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything that happened in an event, newest first, each entry with a readable summary.
         *     Filter by `action` (`event.updated`, or a group like `submission.`), `actor` (email or id)
         *     and `target` (a row id). The event's organisers and admins only.
         */
        get: operations["AuditLogController_forEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/audit.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The event's whole trail, oldest first, as CSV. The event's organisers and admins only. */
        get: operations["AuditLogController_eventCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entries outside any event (logins, accounts, admin grants), with client addresses. Admins only. */
        get: operations["AuditLogController_platform"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The whole event in the organisers' fixtures.json shape (readable by any DOGFOOD portal),
         *     plus an `evenhand` block with what that shape cannot hold. Submitted projects and final
         *     reviews only. Load it into another Evenhand with `cli import <file>`. The event's
         *     organisers and admins only.
         */
        get: operations["EventExportController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/judge-invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A judge invite link for chosen tracks (1 use by default, up to 50 for a panel; 7 days by
         *     default). The token is in this response only. The event's organisers and admins.
         */
        post: operations["JudgesController_createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge-invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What a judge invite is for. Public; does not use it. 410 when expired or used up. */
        get: operations["JudgesController_preview"];
        put?: never;
        /**
         * Become a judge of the event. Refused for anyone on a team in it or organising it
         *     (409 `conflict_of_interest`), existing judges (409) and after judging closes (403).
         */
        post: operations["JudgesController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/judges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The event's judges with their tracks and progress. Its organisers and admins. */
        get: operations["JudgesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/judges/{judgeRef}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the tracks a judge covers. */
        put: operations["JudgesController_setTracks"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/judges/{judgeRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a judge who has not reviewed anything (409 `judge_has_reviews` otherwise). */
        delete: operations["JudgesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/teams.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One row per team member (teams without members get one empty row). */
        get: operations["ExportsController_teams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/submissions.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every submission: status, eligibility, links, duplicate state. */
        get: operations["ExportsController_submissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/assignments.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who reviews what: batch, queue position and state. */
        get: operations["ExportsController_assignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The event's ranking runs, newest first, with whether each still matches the data. */
        get: operations["RankingsController_list"];
        put?: never;
        /**
         * Rank the event from its submitted reviews: normalised scores with uncertainty, tie groups,
         *     a reason per project and hashes of inputs and result. Projects with one review are listed,
         *     not ranked. The event's organisers and admins.
         */
        post: operations["RankingsController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One run with every project: the ranking receipt. */
        get: operations["RankingsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings/{runId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a run as the event's results (409 `ranking_stale` if the data changed since). */
        post: operations["RankingsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published results, with their hashes. Public; 404 until published. */
        get: operations["RankingsController_results"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/results.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The published ranking (else the newest run) as CSV. Organisers and admins. */
        get: operations["RankingsController_resultsCsv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RoleDto: {
            eventId: string;
            /** @enum {string} */
            role: "PARTICIPANT" | "JUDGE" | "ORGANIZER";
            /** @description Fixture id for imported judges, e.g. jdg_24. */
            externalId: string | null;
        };
        MeDto: {
            id: string;
            email: string;
            name: string;
            isAdmin: boolean;
            roles: components["schemas"]["RoleDto"][];
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            name: string;
            /** @description At least 10 characters. */
            password: string;
        };
        TrackRefDto: {
            id: string;
            externalId: string | null;
            name: string;
        };
        ProjectSummaryDto: {
            id: string;
            /** @description Fixture id (e.g. prj_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            title: string;
            tagline: string | null;
            summary: string | null;
            thumbnailUrl: string | null;
            techTags: string[];
            track: components["schemas"]["TrackRefDto"] | null;
            teamName: string;
            submittedAt: string | null;
        };
        ProjectPageDto: {
            items: components["schemas"]["ProjectSummaryDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ProjectDetailDto: {
            id: string;
            /** @description Fixture id (e.g. prj_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            title: string;
            tagline: string | null;
            summary: string | null;
            thumbnailUrl: string | null;
            techTags: string[];
            track: components["schemas"]["TrackRefDto"] | null;
            teamName: string;
            submittedAt: string | null;
            description: string | null;
            repoUrl: string | null;
            demoVideoUrl: string | null;
            liveUrl: string | null;
            imageUrls: string[];
        };
        CreateSubmissionDto: {
            title: string;
            tagline?: string;
            /** @description One-paragraph summary shown on gallery cards. */
            summary?: string;
            /** @description Long description (Markdown is rendered as plain text for now). */
            description?: string;
            /** Format: uri */
            repoUrl?: string;
            /** Format: uri */
            demoVideoUrl?: string;
            /** Format: uri */
            liveUrl?: string;
            techTags?: string[];
            /** @description Track id or fixture id (e.g. trk_01). */
            track?: string;
        };
        SubmissionDto: {
            id: string;
            /** @description Fixture id (e.g. prj_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            teamId: string;
            trackId: string | null;
            title: string;
            tagline: string | null;
            summary: string | null;
            description: string | null;
            repoUrl: string | null;
            demoVideoUrl: string | null;
            liveUrl: string | null;
            techTags: string[];
            /**
             * @description DRAFT until a member submits it; SUBMITTED entries appear in the public gallery.
             * @enum {string}
             */
            status: "DRAFT" | "SUBMITTED";
            /** @description When it was first submitted. */
            submittedAt: string | null;
            createdAt: string;
            updatedAt: string;
        };
        UpdateSubmissionDto: {
            title?: string;
            tagline?: string | null;
            summary?: string | null;
            description?: string | null;
            /** Format: uri */
            repoUrl?: string | null;
            /** Format: uri */
            demoVideoUrl?: string | null;
            /** Format: uri */
            liveUrl?: string | null;
            techTags?: string[];
            /** @description Track id or fixture id (e.g. trk_01) of this event; `null` for no track. */
            track?: string | null;
        };
        JudgeRefDto: {
            /** @description Internal judge id (the judge's EventRole id). */
            id: string;
            /** @description Fixture id, e.g. jdg_24. */
            externalId: string | null;
            name: string;
        };
        ProjectRefDto: {
            id: string;
            externalId: string | null;
            title: string;
        };
        ScoreDto: {
            reviewId: string;
            eventId: string;
            judge: components["schemas"]["JudgeRefDto"];
            project: components["schemas"]["ProjectRefDto"];
            /** @enum {string} */
            status: "DRAFT" | "FINAL";
            /** @description True when the review belonged to a merged duplicate; excluded from ranking. */
            superseded: boolean;
            comment: string;
            /** @description Raw criterion values keyed by criterion key. */
            values: {
                [key: string]: number;
            };
            /** @description Weighted score on the criterion scale; null while the review is incomplete. */
            weightedScore: number | null;
        };
        ScoreListDto: {
            items: components["schemas"]["ScoreDto"][];
        };
        CriterionDto: {
            key: string;
            label: string;
            weight: number;
            min: number;
            max: number;
            order: number;
            /** @description weight / sum of weights, e.g. 0.5 for half of the score. */
            share: number;
        };
        RubricDto: {
            criteria: components["schemas"]["CriterionDto"][];
            /**
             * @description True once any review is final: criteria can then no longer be added or removed and ranges
             *     cannot change (existing scores would stop fitting). Labels and weights stay editable.
             */
            locked: boolean;
        };
        CriterionInputDto: {
            /** @description Stable machine name, e.g. `functionality`. Derived from the label when omitted. */
            key?: string;
            label: string;
            /** @description Relative weight: shares are weight / sum of weights. */
            weight: number;
            min: number;
            max: number;
        };
        RubricInputDto: {
            criteria: components["schemas"]["CriterionInputDto"][];
        };
        RunAssignmentDto: {
            /** @description Reviews wanted per project (default 3). */
            target?: number;
            /** @description Seed for the random tie-breaks, to reproduce a run. A fresh one is drawn when omitted. */
            seed?: number;
        };
        AssignmentJudgeDto: {
            judgeId: string;
            name: string;
            /** @description Assigned in this run. */
            added: number;
            /** @description Assigned in total, across all runs. */
            total: number;
        };
        AssignmentShortfallDto: {
            projectId: string;
            title: string;
            /** @description Reviews it has after the run. */
            have: number;
            /** @description Judges who could review it at all (covering its track, without a conflict). */
            eligibleJudges: number;
        };
        AssignmentRunDto: {
            batch: string;
            seed: number;
            target: number;
            /** @description Projects in judging: submitted, eligible, not a replaced or held duplicate copy. */
            projects: number;
            added: number;
            judges: components["schemas"]["AssignmentJudgeDto"][];
            shortfalls: components["schemas"]["AssignmentShortfallDto"][];
            /**
             * @description Connected groups of judges who share projects. Above 1, some judges' leniency cannot be
             *     compared with the others'.
             */
            components: number;
        };
        QueueItemDto: {
            assignmentId: string;
            /** @description Position in this judge's queue for the event, from 0. */
            position: number;
            projectId: string;
            title: string;
            track: string | null;
            /** @enum {string} */
            state: "DRAFT" | "FINAL" | "NOT_STARTED";
        };
        QueueEventDto: {
            eventId: string;
            eventName: string;
            eventSlug: string;
            judgingClose: string | null;
            /** @description False once judging has closed: reviews can then no longer change. */
            judgingOpen: boolean;
            assigned: number;
            finished: number;
            items: components["schemas"]["QueueItemDto"][];
        };
        JudgeQueueDto: {
            events: components["schemas"]["QueueEventDto"][];
        };
        ReviewProjectDto: {
            id: string;
            title: string;
            tagline: string | null;
            summary: string | null;
            description: string | null;
            repoUrl: string | null;
            demoVideoUrl: string | null;
            liveUrl: string | null;
            techTags: string[];
            track: string | null;
            teamName: string;
        };
        ReviewCriterionDto: {
            key: string;
            label: string;
            min: number;
            max: number;
            /** @description Share of the score, weight / sum of weights. */
            share: number;
        };
        ReviewDto: {
            assignmentId: string;
            eventId: string;
            eventName: string;
            position: number;
            /** @description Assignments in this judge's queue for the event. */
            queueLength: number;
            previousAssignmentId: string | null;
            nextAssignmentId: string | null;
            judgingOpen: boolean;
            project: components["schemas"]["ReviewProjectDto"];
            criteria: components["schemas"]["ReviewCriterionDto"][];
            /** @enum {string} */
            state: "DRAFT" | "FINAL" | "NOT_STARTED";
            values: {
                [key: string]: number;
            };
            comment: string;
            /** @description Weighted score once every criterion is marked, else null. */
            weightedScore: number | null;
            submittedAt: string | null;
        };
        SaveReviewDto: {
            /**
             * @description Marks by criterion key. A draft may leave some out (or send null to clear one); each mark
             *     must be a whole number inside its criterion's range.
             */
            values: {
                [key: string]: unknown;
            };
            comment?: string;
        };
        ProgressTotalsDto: {
            judges: number;
            /** @description Judges with work assigned who have not saved anything yet. */
            judgesNotStarted: number;
            projects: number;
            /** @description Projects with no finished review yet. */
            projectsUnreviewed: number;
            assignments: number;
            finished: number;
            drafts: number;
            notStarted: number;
        };
        ProgressJudgeDto: {
            judgeId: string;
            /** @description Fixture id (e.g. jdg_07) for judges imported from fixtures.json. */
            externalId: string | null;
            name: string;
            email: string;
            tracks: string[];
            assigned: number;
            finished: number;
            drafts: number;
            notStarted: number;
            /** @description When they last saved or submitted anything; null if they have not started. */
            lastActivity: string | null;
            /**
             * @description Gave every project exactly the same marks across 3+ final reviews: their marks say nothing
             *     about how projects differ. (Different marks that average out equal are not flagged.)
             */
            flat: boolean;
        };
        ProgressProjectDto: {
            projectId: string;
            externalId: string | null;
            title: string;
            track: string | null;
            assigned: number;
            finished: number;
            drafts: number;
        };
        ProgressDto: {
            generatedAt: string;
            judgingClose: string | null;
            totals: components["schemas"]["ProgressTotalsDto"];
            judges: components["schemas"]["ProgressJudgeDto"][];
            projects: components["schemas"]["ProgressProjectDto"][];
        };
        EventDto: {
            id: string;
            /** @description Fixture id (e.g. evt_01) when imported from fixtures.json. */
            externalId: string | null;
            slug: string;
            name: string;
            opensAt: string | null;
            submissionsClose: string;
            judgingClose: string | null;
            resultsPublishedAt: string | null;
            /** @description True while the server accepts submissions: opensAt <= now < submissionsClose. */
            submissionsOpen: boolean;
        };
        EventPageDto: {
            items: components["schemas"]["EventDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreateEventDto: {
            name: string;
            /** @description URL name, e.g. `spring-hack-2026`. Derived from the name when omitted. */
            slug?: string;
            /** @description When submissions open. Optional: without it, submissions are open until the close. */
            opensAt?: string;
            /** @description Submissions are accepted only while now < submissionsClose (server clock, UTC). */
            submissionsClose: string;
            /** @description When judging ends. Must be after submissionsClose. */
            judgingClose?: string;
        };
        EventTrackDto: {
            id: string;
            externalId: string | null;
            name: string;
        };
        EventPrizeDto: {
            id: string;
            name: string;
            description: string | null;
            /** @description Null for an overall prize. */
            trackId: string | null;
        };
        EventDetailDto: {
            id: string;
            /** @description Fixture id (e.g. evt_01) when imported from fixtures.json. */
            externalId: string | null;
            slug: string;
            name: string;
            opensAt: string | null;
            submissionsClose: string;
            judgingClose: string | null;
            resultsPublishedAt: string | null;
            /** @description True while the server accepts submissions: opensAt <= now < submissionsClose. */
            submissionsOpen: boolean;
            tracks: components["schemas"]["EventTrackDto"][];
            prizes: components["schemas"]["EventPrizeDto"][];
        };
        UpdateEventDto: {
            name?: string;
            opensAt?: string | null;
            submissionsClose?: string;
            judgingClose?: string | null;
        };
        CreateTrackDto: {
            /** @description Unique within the event. */
            name: string;
        };
        UpdateTrackDto: {
            /** @description Unique within the event. */
            name: string;
        };
        CreatePrizeDto: {
            name: string;
            description?: string;
            /** @description The track this prize is for (id or fixture id, e.g. trk_01). Omit for an overall prize. */
            track?: string;
        };
        UpdatePrizeDto: {
            name?: string;
            description?: string | null;
            track?: string | null;
        };
        OrganizerDto: {
            userId: string;
            name: string;
            email: string;
            /** @description When they became an organiser of this event. */
            since: string;
        };
        AddOrganizerDto: {
            /**
             * Format: email
             * @description An existing account's email: the portal sends no email, so they register first.
             */
            email: string;
        };
        CreateTeamDto: {
            /** @description Unique within the event. */
            name: string;
        };
        TeamMemberDto: {
            userId: string;
            name: string;
            email: string;
            joinedAt: string;
        };
        TeamDto: {
            id: string;
            /** @description Fixture id (e.g. tm_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            name: string;
            members: components["schemas"]["TeamMemberDto"][];
            /** @description The team's current submission in this event (draft or submitted), if it has one. */
            submissionId: string | null;
        };
        MyTeamEventDto: {
            id: string;
            slug: string;
            name: string;
            opensAt: string | null;
            submissionsClose: string;
            /** @description True while the event accepts submissions and team changes. */
            submissionsOpen: boolean;
        };
        MyTeamSubmissionDto: {
            id: string;
            title: string;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED";
            submittedAt: string | null;
        };
        MyTeamDto: {
            team: components["schemas"]["TeamDto"];
            event: components["schemas"]["MyTeamEventDto"];
            /** @description The team's current submission, if it has started one. */
            submission: components["schemas"]["MyTeamSubmissionDto"] | null;
        };
        InviteDto: {
            /** @description The secret. Shown only in this response; the server keeps a hash. */
            token: string;
            /** @description Path to share, relative to the portal, e.g. /invites/<token>. */
            path: string;
            expiresAt: string;
            maxUses: number;
        };
        InvitePreviewDto: {
            teamName: string;
            eventName: string;
            eventSlug: string;
            expiresAt: string;
            usesLeft: number;
        };
        AuditActorDto: {
            id: string;
            name: string;
            email: string;
        };
        AuditEntryDto: {
            /** @description Increasing: a later entry always has a larger id. */
            id: string;
            at: string;
            action: string;
            /** @description Who did it; null for the system (seed, command line). */
            actor: components["schemas"]["AuditActorDto"] | null;
            targetType: string;
            targetId: string | null;
            /** @description The target's name or title, when it can be resolved (also for deleted rows). */
            target: string | null;
            /** @description One readable sentence, e.g. `Ben joined the team "Quiet Hours" with an invite link`. */
            summary: string;
            before: Record<string, never>;
            after: Record<string, never>;
        };
        AuditPageDto: {
            items: components["schemas"]["AuditEntryDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        PlatformAuditEntryDto: {
            /** @description Increasing: a later entry always has a larger id. */
            id: string;
            at: string;
            action: string;
            /** @description Who did it; null for the system (seed, command line). */
            actor: components["schemas"]["AuditActorDto"] | null;
            targetType: string;
            targetId: string | null;
            /** @description The target's name or title, when it can be resolved (also for deleted rows). */
            target: string | null;
            /** @description One readable sentence, e.g. `Ben joined the team "Quiet Hours" with an invite link`. */
            summary: string;
            before: Record<string, never>;
            after: Record<string, never>;
            ip: string | null;
        };
        PlatformAuditPageDto: {
            items: components["schemas"]["PlatformAuditEntryDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreateJudgeInviteDto: {
            /** @description Tracks the judge will cover (ids or fixture ids). Required when the event has tracks. */
            tracks: string[];
            /** @description How many people can accept it: 1 for one person (default), more for a panel link. */
            maxUses?: number;
            /** @description Days until it expires (default 7). */
            days?: number;
        };
        JudgeTrackRefDto: {
            id: string;
            externalId: string | null;
            name: string;
        };
        JudgeInviteDto: {
            /** @description The secret. Shown only in this response; the server keeps a hash. */
            token: string;
            /** @description Path to share, e.g. /judge-invites/<token>. */
            path: string;
            expiresAt: string;
            maxUses: number;
            tracks: components["schemas"]["JudgeTrackRefDto"][];
        };
        JudgeInvitePreviewDto: {
            eventName: string;
            eventSlug: string;
            tracks: string[];
            expiresAt: string;
            usesLeft: number;
        };
        JoinedAsJudgeDto: {
            eventId: string;
            eventSlug: string;
            judgeId: string;
        };
        JudgeDto: {
            /** @description The judge's id in this event (their event role). */
            judgeId: string;
            /** @description Fixture id (e.g. jdg_24) for judges imported from fixtures.json. */
            externalId: string | null;
            userId: string;
            name: string;
            email: string;
            tracks: components["schemas"]["JudgeTrackRefDto"][];
            /** @description Projects assigned to them, and how many of those they have finished. */
            assigned: number;
            finished: number;
            since: string;
        };
        JudgeTracksDto: {
            tracks: string[];
        };
        RankingRowDto: {
            projectId: string;
            externalId: string | null;
            title: string;
            teamName: string;
            track: string | null;
            /** @description 1… for ranked projects; null when there is too little evidence to rank it. */
            rank: number | null;
            /** @description Projects in one group cannot be told apart by the data; null when not ranked. */
            tieGroup: number | null;
            reviews: number;
            rawMean: number;
            normalized: number;
            /** @description Uncertainty of `normalized` (posterior standard deviation). */
            sd: number;
            /** @description Rank by raw mean minus rank by normalized score (positive: moved up). */
            move: number | null;
            /** @description Why the normalized score differs from the raw mean, in one line. */
            reason: string;
        };
        RankingParamsDto: {
            method: string;
            weights: {
                [key: string]: number;
            };
            lambdaB: number;
            lambdaQ: number;
            /** @description The chosen λ sits on the edge of the searched grid. */
            atEdge: boolean;
            looMse: number;
            /** @description Leave-one-out error of predicting every review by the mean of the others. */
            meanOnlyLooMse: number;
            reviews: number;
            /** @description Projects in judging with no final review; not in the ranking. */
            unreviewed: string[];
        };
        RankingDto: {
            rows: components["schemas"]["RankingRowDto"][];
            id: string;
            eventId: string;
            createdAt: string;
            publishedAt: string | null;
            /** @description SHA-256 of the canonical inputs (reviews and weights) and of the canonical result. */
            inputsHash: string;
            outputHash: string;
            /** @description False once the event's final reviews or weights have changed since this run. */
            current: boolean;
            params: components["schemas"]["RankingParamsDto"];
        };
        RankingSummaryDto: {
            id: string;
            eventId: string;
            createdAt: string;
            publishedAt: string | null;
            /** @description SHA-256 of the canonical inputs (reviews and weights) and of the canonical result. */
            inputsHash: string;
            outputHash: string;
            /** @description False once the event's final reviews or weights have changed since this run. */
            current: boolean;
            params: components["schemas"]["RankingParamsDto"];
        };
        PublicResultsDto: {
            eventId: string;
            eventName: string;
            publishedAt: string;
            method: string;
            /** @description Anyone can recompute these from the exported data to check the published result. */
            inputsHash: string;
            outputHash: string;
            tieGroups: number;
            rows: components["schemas"]["RankingRowDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    GalleryController_list: {
        parameters: {
            query?: {
                /** @description Free-text search over title, tagline and summary (case-insensitive). */
                q?: string;
                /** @description Only projects in this track (internal id or fixture id, e.g. trk_01). */
                track?: string;
                /** @description Only projects with this tech tag. */
                tag?: string;
                /** @description Only projects in this event (id, fixture id or slug). */
                event?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPageDto"];
                };
            };
        };
    };
    GalleryController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailDto"];
                };
            };
        };
    };
    SubmissionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    SubmissionController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Submission id or fixture id (prj_01). */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    SubmissionController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Submission id or fixture id (prj_01). */
                ref: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubmissionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    SubmissionController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Submission id or fixture id (prj_01). */
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    JudgingController_ownScores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreListDto"];
                };
            };
        };
    };
    JudgingController_judgeScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                judgeRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreListDto"];
                };
            };
        };
    };
    JudgingController_exportScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RubricController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricDto"];
                };
            };
        };
    };
    RubricController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricInputDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricDto"];
                };
            };
        };
    };
    AssignmentController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAssignmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentRunDto"];
                };
            };
        };
    };
    ReviewsController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeQueueDto"];
                };
            };
        };
    };
    ReviewsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An assignment from your queue. */
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
        };
    };
    ReviewsController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An assignment from your queue. */
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
        };
    };
    ReviewsController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description An assignment from your queue. */
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDto"];
                };
            };
        };
    };
    ProgressController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressDto"];
                };
            };
        };
    };
    EventsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageDto"];
                };
            };
        };
    };
    EventsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    EventsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
        };
    };
    EventsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    TracksController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrackDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTrackDto"];
                };
            };
        };
    };
    TracksController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                /** @description Track id or fixture id (trk_01). */
                trackRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TracksController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                /** @description Track id or fixture id (trk_01). */
                trackRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTrackDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTrackDto"];
                };
            };
        };
    };
    PrizesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrizeDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPrizeDto"];
                };
            };
        };
    };
    PrizesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                prizeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PrizesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                prizeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrizeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPrizeDto"];
                };
            };
        };
    };
    OrganizersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerDto"][];
                };
            };
        };
    };
    OrganizersController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddOrganizerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizerDto"];
                };
            };
        };
    };
    OrganizersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TeamsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
        };
    };
    TeamsController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyTeamDto"][];
                };
            };
        };
    };
    TeamsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id or fixture id (tm_01). */
                teamRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
        };
    };
    TeamsController_createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team id or fixture id (tm_01). */
                teamRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteDto"];
                };
            };
        };
    };
    TeamsController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitePreviewDto"];
                };
            };
        };
    };
    TeamsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamDto"];
                };
            };
        };
    };
    AuditLogController_forEvent: {
        parameters: {
            query?: {
                /** @description An action (`event.updated`) or a group ending in a dot (`submission.`). */
                action?: string;
                /** @description Only what this person did: their email or user id. */
                actor?: string;
                /** @description Only entries about this row (e.g. a submission id). */
                target?: string;
            };
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPageDto"];
                };
            };
        };
    };
    AuditLogController_eventCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditLogController_platform: {
        parameters: {
            query?: {
                /** @description An action (`event.updated`) or a group ending in a dot (`submission.`). */
                action?: string;
                /** @description Only what this person did: their email or user id. */
                actor?: string;
                /** @description Only entries about this row (e.g. a submission id). */
                target?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformAuditPageDto"];
                };
            };
        };
    };
    EventExportController_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    JudgesController_createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJudgeInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeInviteDto"];
                };
            };
        };
    };
    JudgesController_preview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeInvitePreviewDto"];
                };
            };
        };
    };
    JudgesController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinedAsJudgeDto"];
                };
            };
        };
    };
    JudgesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeDto"][];
                };
            };
        };
    };
    JudgesController_setTracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                /** @description Judge id or fixture id (jdg_24). */
                judgeRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeTracksDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeDto"];
                };
            };
        };
    };
    JudgesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
                /** @description Judge id or fixture id (jdg_24). */
                judgeRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportsController_teams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportsController_submissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExportsController_assignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RankingsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingSummaryDto"][];
                };
            };
        };
    };
    RankingsController_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingDto"];
                };
            };
        };
    };
    RankingsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingDto"];
                };
            };
        };
    };
    RankingsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingDto"];
                };
            };
        };
    };
    RankingsController_results: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicResultsDto"];
                };
            };
        };
    };
    RankingsController_resultsCsv: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
