/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database readiness. Used by the compose healthcheck. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email + password login. Sets the httpOnly `session` cookie and returns the user. */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates an account (no event roles yet) and logs it in. */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ends the current browser session. */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user and their roles per event. 401 when not logged in. */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public gallery with search and filters. Acceptance checks 1 and 2 read this route. */
        get: operations["GalleryController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One public project, by internal id or fixture id (e.g. prj_01). */
        get: operations["GalleryController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create your team's draft. Refused with 403 `submissions_closed` once the event's
         *     deadline has passed, before the body is validated (acceptance check 3).
         */
        post: operations["SubmissionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judge/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own scores. Judges only: participants get 403 (acceptance checks 4 and 6). */
        get: operations["JudgingController_ownScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/judges/{judgeRef}/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One judge's scores, by internal id or fixture id (e.g. jdg_24). Only that judge, the
         *     event's organisers and admins may read them; any other judge gets 403 (acceptance check 5).
         */
        get: operations["JudgingController_judgeScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}/export/scores.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every review in the event as CSV. Organisers and admins only (acceptance check 7). */
        get: operations["JudgingController_exportScores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every event, newest deadline first. Public. */
        get: operations["EventsController_list"];
        put?: never;
        /**
         * Create an event; you become its organiser. Admins and existing organisers only (403
         *     otherwise). The slug is derived from the name unless given; a taken slug is 409.
         */
        post: operations["EventsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{eventRef}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One event with its tracks and prizes. Public. */
        get: operations["EventsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the name or dates. Organisers of this event and admins only. */
        patch: operations["EventsController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /** Format: email */
            email: string;
            password: string;
        };
        RoleDto: {
            eventId: string;
            /** @enum {string} */
            role: "PARTICIPANT" | "JUDGE" | "ORGANIZER";
            /** @description Fixture id for imported judges, e.g. jdg_24. */
            externalId: string | null;
        };
        MeDto: {
            id: string;
            email: string;
            name: string;
            isAdmin: boolean;
            roles: components["schemas"]["RoleDto"][];
        };
        RegisterDto: {
            /** Format: email */
            email: string;
            name: string;
            /** @description At least 10 characters. */
            password: string;
        };
        TrackRefDto: {
            id: string;
            externalId: string | null;
            name: string;
        };
        ProjectSummaryDto: {
            id: string;
            /** @description Fixture id (e.g. prj_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            title: string;
            tagline: string | null;
            summary: string | null;
            thumbnailUrl: string | null;
            techTags: string[];
            track: components["schemas"]["TrackRefDto"] | null;
            teamName: string;
            submittedAt: string | null;
        };
        ProjectPageDto: {
            items: components["schemas"]["ProjectSummaryDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        ProjectDetailDto: {
            id: string;
            /** @description Fixture id (e.g. prj_01) when imported from fixtures.json. */
            externalId: string | null;
            eventId: string;
            title: string;
            tagline: string | null;
            summary: string | null;
            thumbnailUrl: string | null;
            techTags: string[];
            track: components["schemas"]["TrackRefDto"] | null;
            teamName: string;
            submittedAt: string | null;
            description: string | null;
            repoUrl: string | null;
            demoVideoUrl: string | null;
            liveUrl: string | null;
            imageUrls: string[];
        };
        CreateSubmissionDto: {
            title: string;
            tagline?: string;
            /** @description One-paragraph summary shown on gallery cards. */
            summary?: string;
            /** @description Long description (Markdown is rendered as plain text for now). */
            description?: string;
            /** Format: uri */
            repoUrl?: string;
            /** Format: uri */
            demoVideoUrl?: string;
            /** Format: uri */
            liveUrl?: string;
            techTags?: string[];
            /** @description Track id or fixture id (e.g. trk_01). */
            track?: string;
        };
        SubmissionDto: {
            id: string;
            eventId: string;
            teamId: string;
            title: string;
            /** @enum {string} */
            status: "DRAFT" | "SUBMITTED";
            createdAt: string;
        };
        JudgeRefDto: {
            /** @description Internal judge id (the judge's EventRole id). */
            id: string;
            /** @description Fixture id, e.g. jdg_24. */
            externalId: string | null;
            name: string;
        };
        ProjectRefDto: {
            id: string;
            externalId: string | null;
            title: string;
        };
        ScoreDto: {
            reviewId: string;
            eventId: string;
            judge: components["schemas"]["JudgeRefDto"];
            project: components["schemas"]["ProjectRefDto"];
            /** @enum {string} */
            status: "DRAFT" | "FINAL";
            /** @description True when the review belonged to a merged duplicate; excluded from ranking. */
            superseded: boolean;
            comment: string;
            /** @description Raw criterion values keyed by criterion key. */
            values: {
                [key: string]: number;
            };
            /** @description Weighted score on the criterion scale; null while the review is incomplete. */
            weightedScore: number | null;
        };
        ScoreListDto: {
            items: components["schemas"]["ScoreDto"][];
        };
        EventDto: {
            id: string;
            /** @description Fixture id (e.g. evt_01) when imported from fixtures.json. */
            externalId: string | null;
            slug: string;
            name: string;
            opensAt: string | null;
            submissionsClose: string;
            judgingClose: string | null;
            resultsPublishedAt: string | null;
            /** @description True while the server accepts submissions: opensAt <= now < submissionsClose. */
            submissionsOpen: boolean;
        };
        EventPageDto: {
            items: components["schemas"]["EventDto"][];
            page: number;
            pageSize: number;
            total: number;
        };
        CreateEventDto: {
            name: string;
            /** @description URL name, e.g. `spring-hack-2026`. Derived from the name when omitted. */
            slug?: string;
            /** @description When submissions open. Optional: without it, submissions are open until the close. */
            opensAt?: string;
            /** @description Submissions are accepted only while now < submissionsClose (server clock, UTC). */
            submissionsClose: string;
            /** @description When judging ends. Must be after submissionsClose. */
            judgingClose?: string;
        };
        EventTrackDto: {
            id: string;
            externalId: string | null;
            name: string;
        };
        EventPrizeDto: {
            id: string;
            name: string;
            description: string | null;
            /** @description Null for an overall prize. */
            trackId: string | null;
        };
        EventDetailDto: {
            id: string;
            /** @description Fixture id (e.g. evt_01) when imported from fixtures.json. */
            externalId: string | null;
            slug: string;
            name: string;
            opensAt: string | null;
            submissionsClose: string;
            judgingClose: string | null;
            resultsPublishedAt: string | null;
            /** @description True while the server accepts submissions: opensAt <= now < submissionsClose. */
            submissionsOpen: boolean;
            tracks: components["schemas"]["EventTrackDto"][];
            prizes: components["schemas"]["EventPrizeDto"][];
        };
        UpdateEventDto: {
            name?: string;
            opensAt?: string | null;
            submissionsClose?: string;
            judgingClose?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    GalleryController_list: {
        parameters: {
            query?: {
                /** @description Free-text search over title, tagline and summary (case-insensitive). */
                q?: string;
                /** @description Only projects in this track (internal id or fixture id, e.g. trk_01). */
                track?: string;
                /** @description Only projects with this tech tag. */
                tag?: string;
                /** @description Only projects in this event (id, fixture id or slug). */
                event?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPageDto"];
                };
            };
        };
    };
    GalleryController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailDto"];
                };
            };
        };
    };
    SubmissionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: unknown;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionDto"];
                };
            };
        };
    };
    JudgingController_ownScores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreListDto"];
                };
            };
        };
    };
    JudgingController_judgeScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                judgeRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreListDto"];
                };
            };
        };
    };
    JudgingController_exportScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPageDto"];
                };
            };
        };
    };
    EventsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
    EventsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetailDto"];
                };
            };
        };
    };
    EventsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Event id, fixture id (evt_01) or slug. */
                eventRef: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDto"];
                };
            };
        };
    };
}
